### ISSUE TITLE
Use a "status view" instead of a window

### ISSUE THREAD

**Issue by humdingerb** [Perelandra0x309/depots#2]
If a repo isn't as huge as e.g. clasqm's repo, en/disabling it doesn't take a second. Showing and hiding a window is distracting. You might consider a "status view" to the left of the Enable/Disable instead.

Not sure a barber pole is really needed, poping that one up for half a second is also more distracting than helpful. One can go to all kinds of lengths to make it nicer (I doubt the need a bit, though...):
- Make sure the status text is only shown if the operation has taken more than a second.
- If the status text is shown, show it at least two seconds, so the user notices it and can read it.
- Animate three running dots instead of the barber pole for long operations.

**Comment by Perelandra0x309** [comment]
Disabling is very quick.  Enabling usually always takes a few seconds since the repo server must be contacted by the package manager.  I did at one point have the task window stay open upon completion, and you would press an "OK" button or hit ESC to dismiss it.

Yes maybe a small status bar would work well.  I was planning at some point finding the Haiku source for the move/copy/empty trash window that is used and see if there was anything there that would inspire me.  Maybe there could be a small status bar and when tasks are kicked off there could be a stop button (I don't see a need for a pause button).

**Comment by humdingerb** [comment]
Another idea instead of a status view: Animated characters where the checkmark appears in the Enabled column, like ⋮ ⋰ ⋯ ⋱ ⋯ (or a spinning wheel etc. which I didn't find as UTF characters).

Instead of a cancel/stop button which will blink out of existence most of the time, I'd rather see the code monitor progress and have a sensible timeout that triggers an alert window, if there's no or minimal traffic to the targetted server for 8 seconds. The value for the smallest sensible value can be experimented with...

**Comment by Perelandra0x309** [comment]
Ha, that is too funny!  I had almost the exact same idea for the status as I was falling asleep last night.  I was thinking of putting "..." for each selected list item so you could see which ones are "in the queue" for processing.  Then as each was being enabled/disabled put an "Enabling..." or "Disabling..." with the trailing "..." being animated so the user could see which was currently being processed.  Then as each completed set the final status to the check mark or nothing.  I have an idea how to do this with messaging and Pulse.  I was also going to experiment with changing the cursor as another visual clue, maybe B_CURSOR_ID_PROGRESS?  I don't recall what that one is so I will have to try it.

I could change one of the buttons to read "Cancel" as you said if there is an unusual amount of time when no further messages have been received from the worker thread.

**Comment by humdingerb** [comment]
The cursors are at http://cgit.haiku-os.org/haiku/tree/data/artwork/cursors as I-O-M files.
This is the Progress pointer:

![progress](https://cloud.githubusercontent.com/assets/6107158/21099683/e1bd1a88-c06f-11e6-88bc-3cbac49940c4.png)

I'm not a huge fan of cursor changes for that kind of thing. Reminds to much of Window's hourglass, and suggests that the app now won't respond to input.

Instead of Pulse() I'd recommend creating a BMessageRunner() that fires off a BMessage every half second or something. I know I had problems changing the Pulse() rate and went with BMessageRunner() when Rene pointed me to it.

Another possibility, which has the advantage to again convey the progress to the user: go with a progress bar in the BColumnListView. I don't know how HaikuDepot does it exactly, but it is nifty...

**Comment by Perelandra0x309** [comment]
Thanks for the MessageRunner tip.

Oh, I found this in ColumnListView.h, I'll have to play with it:

// The status view is a little area in the lower left hand corner.
void	AddStatusView(BView* view);

That must be how the Tracker shows its little barber pole when updating the view.

**Comment by Perelandra0x309** [comment]
I've made a lot of progress on this, eliminating the task progress window and presenting cues in the Enabled column.   I redesigned the task management so that you can add more enable/disable requests while current tasks are running (you couldn't do that before just because of the nature of the modal task window didn't allow you to interact with the main window).  I also implemented invoking a change with a mouse click or keyboard.  Checkout branch v1.0.1

I haven't done anything fancy with a MessageRunner or status view yet, and need to think of a good way to present the user with an option to cancel running tasks.

**Comment by humdingerb** [comment]
Looks very good. Maybe the status text (which currently sticks at "Status: Testing...") could use a 1 pt smaller font and a dark grey instead of black.
WRT cancelling an operation, it's tricky. I still think using a sensible timeout, maybe after which an alert asks "Enabling|Disabling the depot takes an unusually long time. Cancel?", should cover most cases.
Plus, closing the window while a transaction is running could also pop up an alert, asking if the transaction should really be aborted..
I'd wait for anything more elaborate until the real life usage shows there's a need.

**Comment by Perelandra0x309** [comment]
Basic status view is done.  It will only display text if there are two or more repo changes in queue.  So if you just mouse click individual repos the status view won't say anything (unless you click other ones really fast!) so it won't be distracting.

>closing the window while a transaction is running could also pop up an alert, asking if the transaction should really be aborted..

Already implemented :-)

Still thinking about maybe doing a message runner to check if a task has been running for more than 15 seconds or something.

**Comment by Perelandra0x309** [comment]
OK give branch v1.1.0 a try.  I decided to bump up the version by a middle count because I did a lot with making the change tasks multi-threaded (wow is it fast now) and I am now using the actual classes from the package kit instead of just doing system calls to pkgman.

I made a timer for each task that times out at 10 seconds and displays a message.  The user has the option to kill the task now, or "Keep Trying", which will reset the timer to 30 seconds and wait again before displaying another message.  You can try this out by uncommenting the sleep(60); line in the TaskLooper::_DoTask fundtion which I used for testing.

Also the final "Changes completed" message in the list status view (when kicking off multiple changes) will display for 3 seconds before disappearing so the user has a chance to read it.  What do you think of the timing?

**Comment by humdingerb** [comment]
Sorry for the delayed reply... Looks like you make nice progress.

I'll just write all the tiny things I noticed in here. Tell me if I should open separate issues instead:

- If more than one task is timing out, the opened alerts pop up on top of each other.
- The alert should better pop up on top or near the main windo, not center screen.
- The alert text should be in perfect English. :) E.g. "The task for the depot "Name of Depot" has completed."
- The buttons in the alert should be right-aligned.
- When adding a depot, it may look nice to have the modal window pop up to align to the bottom of the window and make it the same width, see https://lut.im/l4t0PBbKtK/bvOUP66GhP6EE79B.png
- The modal depot-adding window should not have a resize corner (or make it resizable):
- Buttons in the modal depot-adding window should be right-aligned with "Add" the default button.
- In the status view a space is missing after the ":" >  "Changes pending:2"
- There's a horizontal line missing from the +/- button group to the right where it should meet the scrollbar.

Tiny stuff... Depots is looking great! :)

**Comment by Perelandra0x309** [comment]
Yeah some little stuff to cleanup.  Not sure what you mean by the last point.  This is what it looks like on my hrev50702:
https://dl.dropboxusercontent.com/u/45521074/screenshot1.png

Oh and a new issue would be good, this one is getting a bit long, and really should be closed since the original issue is complete.

**Comment by humdingerb** [comment]
Here is how it looks with the default Noto Sans 12pt font:

![screenshot1](https://cloud.githubusercontent.com/assets/6107158/21447613/881c4e02-c8d7-11e6-8b90-9cd8747113ca.png)

All is OK when changing to DejaVu 12pt.
Seems to be an Haiku issue. Maybe in layout management or the updated un-tweaked freetype?

**Comment by Perelandra0x309** [comment]
Moving your other GUI issues listed above to #4 
Try this again.  I figured out the issue with some fonts being larger than the space I was allocating.  I modified the layout so the view are strictly limited in size.

**Comment by humdingerb** [comment]
Indeed, fixed. Well done. :)

**Comment by Perelandra0x309** [comment]
Status view now complete.
